---
title: "final"
output: html_document
date: "2023-06-03"
---

  
```{r setup, include=FALSE}

rm(list=ls())

library(flexdashboard)
library(RSelenium)
library(XML)
library(rvest)
library(stringr)
library(knitr)
library(dplyr)
library(tidyr)
library(lubridate)
library(httr)
library(readxl)
library(writexl)
library(jsonlite)
library(kableExtra)
library(DT)

rD <- rsDriver(port=4740L, chromever="113.0.5672.63")
remDr <- rD$client

## 날짜 및 시간 설정
now <- Sys.time()
today <- format(Sys.time(), "%Y.%m.%d.")

## 수익증권 수집 함수 선언
B02 <- function(b02){URL <- "https://kind.krx.co.kr/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeBenfcert"
remDr$navigate(URL)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

Stack <- NULL
n <- 2
for (i in 1:n){
  Sys.sleep(2)
pattern <- "#companysum"
name <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>%
  str_trim()

pattern <- "#main-contents > section:nth-child(1) > table > tbody > tr > td:nth-child(2)"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>%
  str_trim()

pattern <- "#main-contents > section:nth-child(1) > table > tbody > tr > td:nth-child(4) > a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>%
  str_trim()

data <- cbind(name,date,title)
Stack <- rbind(Stack,data)
}}



## 벤처인 수집 함수 선언
venture <- function(venturelist) {
URL <- "https://www.smes.go.kr/venturein/pbntc/searchVntrCmp"
remDr$navigate(URL)

Stack <- NULL
n <- 3
for (i in 1:n){
Sys.sleep(2)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)


name <- res %>%
  html_nodes(".c_tit") %>%
  html_text()


number <- res %>%
  html_nodes(".ta_l:nth-child(3)") %>%
  html_text()


data <- cbind(name,number)
Stack <- rbind(Stack,data)

pattern <- ".active+ a" # Selector Gadget
element <- remDr$findElement(using = "css", pattern)
element$clickElement()
}
  
}

## 유가증권상장리스트
kospi <-function(name) {
URL <- "https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage"
remDr$navigate(URL)

Sys.sleep(2)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

# 페이지 반복 횟수 설정
num_pages <- 2

# 변수를 저장할 리스트 초기화
name_list <- list()
work_list <- list()
use_list <- list()
date_list <- list()
month_list <- list()
king_list <- list()

Stack <- NULL
num_pages <- 2
# 반복문을 사용하여 페이지를 자동으로 넘기고 변수 추출하는 코드
for (i in 1:num_pages) {
  # 변수 추출
  name <- res %>%
    html_nodes("#companysum") %>%
    html_text()
  name
  name_list <- c(name_list, name)
  
  work <- res %>%
    html_nodes("#main-contents > section.scrarea.type-00 > table > tbody > tr.first > td:nth-child(2)") %>%
    html_text()
  work
  work_list <- c(work_list, work)
  
  use <- res %>%
    html_nodes(".textOverflow+ .textOverflow") %>%
    html_text()
  use_list <- c(use_list, use)
  
  date <- res %>%
    html_nodes(".textOverflow+ .txc") %>%
    html_text()
  date_list <- c(date_list, date)
  
  king <- res %>%
    html_nodes(".txc:nth-child(6)") %>%
    html_text() %>%
    str_trim()
  king_list <- c(king_list, king)
  
 
  data <- cbind(name_list,work_list,use_list,date_list,king_list)
  Stack <- rbind(Stack,data)
  
  # 페이지 넘기는 명령어 실행
  pattern <- ".next"
  element <- remDr$findElement("css", pattern)
  element$clickElement()
  
  # 2초 대기
  Sys.sleep(2)
  
  
}

}

```

1. News
=======================================================================

Column {data-width=500}
-----------------------------------------------------------------------
### Chart A1 (**Issued at `r now`**)

**벤처기업리스트**

```{r}
URL <- "https://www.smes.go.kr/venturein/pbntc/searchVntrCmp"

remDr$navigate(URL)

Sys.sleep(3)


txt <- remDr$getPageSource()[[1]]

res <- read_html(txt)

Stack <- NULL
n <- 3
for (i in 1:n){
Sys.sleep(2)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)


name <- res %>%
  html_nodes(".c_tit") %>%
  html_text()


number <- res %>%
  html_nodes(".ta_l:nth-child(3)") %>%
  html_text()


data <- cbind(name,number)
Stack <- rbind(Stack,data)

pattern <- ".active+ a" # Selector Gadget
element <- remDr$findElement(using = "css", pattern)
element$clickElement()
}
```



### Chart A2

**주식발행내역**

```{r}
URL <- "https://kind.krx.co.kr/corpgeneral/stockissuelist.do?method=loadInitPage"

remDr$navigate(URL)

Sys.sleep(3)
# remDr %>% setTimeout(type = "page load", milliseconds = 10000)

txt <- remDr$getPageSource()[[1]]

res <- read_html(txt)

name_list <- list()
date_list <- list()
way_list <- list()
total_list <- list()
won_list <- list()
reason_list <- list()

Stack <- NULL
num_pages <- 2
# 반복문을 사용하여 페이지를 자동으로 넘기고 변수 추출하는 코드
for (i in 1:num_pages) {
  # 변수 추출
  name <- res %>%
    html_nodes("#companysum") %>%
    html_text()
  name_list <- c(name_list, name)
  
  date <- res %>%
    html_nodes(".first+ .txc") %>%
    html_text()
  date_list <- c(date_list, date)
  
  way <- res %>%
    html_nodes(".txc+ .txc") %>%
    html_text()
  way_list <- c(way_list, way)
  
  total <- res %>%
    html_nodes(".txc+ .txr") %>%
    html_text()
  total_list <- c(total_list, total)
  
  won <- res %>%
    html_nodes(".txr+ .txr") %>%
    html_text() %>%
    str_trim()
  won_list <- c(won_list, won)
  
  reason <- res %>%
    html_nodes(".txr~ .txr+ td") %>%
    html_text() %>%
    str_trim()
  reason_list <- c(reason_list, reason)
  data <- cbind(name_list,date_list,way_list,total_list,won_list,reason_list)
  Stack <- rbind(Stack,data)

    # 페이지 넘기는 명령어 실행
  pattern <- ".next"
  element <- remDr$findElement("css", pattern)
  element$clickElement()
  
  # 2초 대기
  Sys.sleep(2)
  
  
  }
```



Column {data-width=500}
-----------------------------------------------------------------------

### Chart B1

[리스트: 수익증권](https://kind.krx.co.kr/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeBenfcert)

```{r, include=FALSE}
URL <- "https://kind.krx.co.kr/disclosure/disclosurebystocktype.do?method=searchDisclosureByStockTypeBenfcert"
remDr$navigate(URL)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

Stack <- NULL
n <- 2
for (i in 1:n){
  Sys.sleep(2)
pattern <- "#companysum"
name <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>%
  str_trim()

pattern <- "#main-contents > section:nth-child(1) > table > tbody > tr > td:nth-child(2)"
date <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>%
  str_trim()

pattern <- "#main-contents > section:nth-child(1) > table > tbody > tr > td:nth-child(4) > a"
title <- res %>% 
  html_nodes(pattern) %>% 
  html_text() %>%
  str_trim()

data <- cbind(name,date,title)
Stack <- rbind(Stack,data)
}

```



### Chart B2

[유가증권상장리스트](https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage)

```URL <- "https://kind.krx.co.kr/corpgeneral/corpList.do?method=loadInitPage"
remDr$navigate(URL)

Sys.sleep(2)

txt <- remDr$getPageSource()[[1]]
res <- read_html(txt)

# 페이지 반복 횟수 설정
num_pages <- 2

# 변수를 저장할 리스트 초기화
name_list <- list()
work_list <- list()
use_list <- list()
date_list <- list()
month_list <- list()
king_list <- list()

Stack <- NULL
num_pages <- 2
# 반복문을 사용하여 페이지를 자동으로 넘기고 변수 추출하는 코드
for (i in 1:num_pages) {
  # 변수 추출
  name <- res %>%
    html_nodes("#companysum") %>%
    html_text()
  name
  name_list <- c(name_list, name)
  
  work <- res %>%
    html_nodes("#main-contents > section.scrarea.type-00 > table > tbody > tr.first > td:nth-child(2)") %>%
    html_text()
  work
  work_list <- c(work_list, work)
  
  use <- res %>%
    html_nodes(".textOverflow+ .textOverflow") %>%
    html_text()
  use_list <- c(use_list, use)
  
  date <- res %>%
    html_nodes(".textOverflow+ .txc") %>%
    html_text()
  date_list <- c(date_list, date)
  
  king <- res %>%
    html_nodes(".txc:nth-child(6)") %>%
    html_text() %>%
    str_trim()
  king_list <- c(king_list, king)
  
 
  data <- cbind(name_list,work_list,use_list,date_list,king_list)
  Stack <- rbind(Stack,data)
  
  # 페이지 넘기는 명령어 실행
  pattern <- ".next"
  element <- remDr$findElement("css", pattern)
  element$clickElement()
  
  # 2초 대기
  Sys.sleep(2)
  
}
```